export const records = [
    {
        record: {
            icon: "/pricing/basic-g.png",
            name: "پلن پایه",
            desc: "برای اشخاص و رستوران / کافی شاپ های کوچک",
            limitations: [
                { limit: "qr-scan-limit", value: Infinity, valueType: "Number" },
                { limit: "category-limit", value: Infinity, valueType: "Number" },
                { limit: "menu-item-limit", value: Infinity, valueType: "Number" },
                { limit: "brand-details-in-menu", value: true, valueType: "Boolean" },
                { limit: "multiple-language-limit", value: 2, valueType: "Number" },
                { limit: "ticket-and-support", value: true, valueType: "Boolean" },
                { limit: "menu-templates", value: false, valueType: "Boolean" },
                { limit: "branch-limit-count", value: 1, valueType: "Number" },
                { limit: "staff-limit-count", value: 5, valueType: "Number" },
                { limit: "customize-qr", value: false, valueType: "Boolean" },
                { limit: "restaurant-detailed-info", value: false, valueType: "Boolean" },
                { limit: "menu-item-like", value: false, valueType: "Boolean" },
                { limit: "analytics", value: false, valueType: "Boolean" },
                { limit: "item-highlighting", value: false, valueType: "Boolean" },
                { limit: "ordering-system", value: false, valueType: "Boolean" },
                { limit: "server-call-button", value: false, valueType: "Boolean" },
                { limit: "logo-in-qr", value: false, valueType: "Boolean" },
                { limit: "menu-item-coupling", value: false, valueType: "Boolean" },
                { limit: "menu-tag-option", value: false, valueType: "Boolean" },
                { limit: "customizable-category-logo", value: false, valueType: "Boolean" },
                { limit: "customer-review", value: false, valueType: "Boolean" },
            ],
            listings: [
                "میزان اسکن کد نامحدود",
                "کاملا قابل شخصی سازی",
                "افزودن دسته بندی و ایتم به صورت نامحدود",
                "درج لوگو و نام برند در منو",
                "امکان ساخت منو چندزبانه",
                "پشتیبانی رایگان",
            ],
            monthlyPrice: 0,
            halfYearPrice: 0,
            yearlyPrice: 0,
        },
        translation: {
            en: {
                name: "Basic Plan",
                desc: "For individuals or small restaurants and small coffee shops",
                listings: [
                    "Unlimited QR scans",
                    "Fully customizable",
                    "Unlimited Category and menu items",
                    "Brand logo and name in the menu",
                    "Multiple language option",
                    "Ticketing and support system",
                ],
            },
        },
    },
    {
        record: {
            icon: "/pricing/standard-g.png",
            name: "پلن استاندارد",
            desc: "برای کسب و کار ها و رستوران هایی که بیش از یک شعبه دارند",
            limitations: [
                { limit: "qr-scan-limit", value: Infinity, valueType: "Number" },
                { limit: "category-limit", value: Infinity, valueType: "Number" },
                { limit: "menu-item-limit", value: Infinity, valueType: "Number" },
                { limit: "brand-details-in-menu", value: true, valueType: "Boolean" },
                { limit: "multiple-language-limit", value: 4, valueType: "Number" },
                { limit: "ticket-and-support", value: true, valueType: "Boolean" },
                { limit: "menu-templates", value: true, valueType: "Boolean" },
                { limit: "branch-limit-count", value: 5, valueType: "Number" },
                { limit: "staff-limit-count", value: 10, valueType: "Number" },
                { limit: "customize-qr", value: true, valueType: "Boolean" },
                { limit: "restaurant-detailed-info", value: true, valueType: "Boolean" },
                { limit: "menu-item-like", value: true, valueType: "Boolean" },
                { limit: "analytics", value: true, valueType: "Boolean" },
                { limit: "item-highlighting", value: true, valueType: "Boolean" },
                { limit: "ordering-system", value: false, valueType: "Boolean" },
                { limit: "server-call-button", value: false, valueType: "Boolean" },
                { limit: "logo-in-qr", value: false, valueType: "Boolean" },
                { limit: "menu-item-coupling", value: false, valueType: "Boolean" },
                { limit: "menu-tag-option", value: false, valueType: "Boolean" },
                { limit: "customizable-category-logo", value: false, valueType: "Boolean" },
                { limit: "customer-review", value: false, valueType: "Boolean" },
            ],
            listings: [
                "دسترسی به قالب های مختلف منو",
                "امکان ساخت تا 5 شعبه",
                "امکان شخصی سازی کد کیو ار",
                "صفحه اختصاصی برای نمایش اطلاعات کامل رستوران",
                "گزینه علاقه مندی برای ایتم های منو",
                "قابلیت تحلیل و نمایش امار",
                "برجسته کردن ایتم ها و نمایش ایتم های تمام شده",
            ],
            monthlyPrice: 150_000,
            halfYearPrice: 900_000,
            yearlyPrice: 1_620_000,
        },
        translation: {
            en: {
                name: "Standard Plan",
                desc: "For businesses and restaurants with more than one branch",
                listings: [
                    "Multiple menu templates",
                    "Create up to 5 branches",
                    "Customizable QR code",
                    "Restaurant info at bottom of menu",
                    "Menu item like option",
                    "Analytics for scans and reviews",
                    "Item highlight and sold out options",
                ],
            },
        },
    },
    {
        record: {
            icon: "/pricing/pro-g.png",
            name: "پلن حرفه ای",
            desc: "برای کسب و کارهایی که به بیش از یک منو دیجیتال نیاز دارند",
            limitations: [
                { limit: "qr-scan-limit", value: Infinity, valueType: "Number" },
                { limit: "category-limit", value: Infinity, valueType: "Number" },
                { limit: "menu-item-limit", value: Infinity, valueType: "Number" },
                { limit: "brand-details-in-menu", value: true, valueType: "Boolean" },
                { limit: "multiple-language-limit", value: 10, valueType: "Number" },
                { limit: "ticket-and-support", value: true, valueType: "Boolean" },
                { limit: "menu-templates", value: true, valueType: "Boolean" },
                { limit: "branch-limit-count", value: 15, valueType: "Number" },
                { limit: "staff-limit-count", value: 15, valueType: "Number" },
                { limit: "customize-qr", value: true, valueType: "Boolean" },
                { limit: "restaurant-detailed-info", value: true, valueType: "Boolean" },
                { limit: "menu-item-like", value: true, valueType: "Boolean" },
                { limit: "analytics", value: true, valueType: "Boolean" },
                { limit: "item-highlighting", value: true, valueType: "Boolean" },
                { limit: "ordering-system", value: true, valueType: "Boolean" },
                { limit: "server-call-button", value: true, valueType: "Boolean" },
                { limit: "logo-in-qr", value: true, valueType: "Boolean" },
                { limit: "menu-item-coupling", value: true, valueType: "Boolean" },
                { limit: "menu-tag-option", value: true, valueType: "Boolean" },
                { limit: "customizable-category-logo", value: true, valueType: "Boolean" },
                { limit: "customer-review", value: true, valueType: "Boolean" },
            ],
            listings: [
                "سیستم مدیریت سفارشات و سفارشگیری",
                "امکان ساخت تا 15 شعبه",
                "دکمه درخواست گارسون",
                "امکان درج لوگو رستوران در کد کیو ار",
                "امکان زوج کردن ایتم های منو",
                "قابلیت اضافه کردن تگ هی مختلف به ایتم ها",
                "امکان شخصی سازی عکس دسته بندی ها",
                "قابلیت ثبت نظر توسط مشتریان",
            ],
            monthlyPrice: 350_000,
            halfYearPrice: 2_100_000,
            yearlyPrice: 3_780_000,
        },
        translation: {
            en: {
                name: "Pro Plan",
                desc: "For businesses that need more than a digital menu",
                listings: [
                    "Ordering system",
                    "Create up to 15 branches",
                    "Server call button in the menu",
                    "Restaurant logo in the QR code",
                    "Menu item coupling",
                    "Discount tags on menu items",
                    "Customizable category logos",
                    "Customer review option",
                ],
            },
        },
    },
];
