name: Docker Build and Upload

on:
    push:
        branches:
            - master # Change this to your branch name if needed

jobs:
    build_and_upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              run: docker build -t your-image-name .

            - name: Transfer Docker image to Droplet
              run: |
                  docker save your-image-name | gzip | doctl compute ssh your-droplet-name --ssh-private-key-path ./id_rsa -- tar -xzf - -C /path/to/save/image

            - name: Transfer Docker image to VPS
              run: |
                  docker save your-image-name | gzip | ssh -i ./path/to/private_key user@your-vps-ip "cat | docker load"
